### ISSUE TITLE
Doesn't provide CLI usage like live-server

### ISSUE THREAD

**Issue by feljx** [yandeu/five-server#12]
I want to control my workflow through NPM scripts rather than using the VS Code extension, and I'd like to avoid using yet another config file just for the dev server.
`live-server` provides CLI commands for this purpose, it doesn't seem like this project does,
stuff like `--no-browser` and `--open=PATH`.

I can contribute a PR if you are open to including CLI commands.

**Comment by yandeu** [comment]
This already exists but is not well documented. But, you can of course also use a config file for your workflow.
