### ISSUE TITLE
Five server page crashes

### ISSUE THREAD

**Issue by garma21** [yandeu/five-server#121]
**Describe the bug**
The five server page crashes in the chrome browser after I enable device tools in devTools. Please solve this problem or give a guide on how to get rid of this error

**Have a question?**
Join the [discussions](https://github.com/yandeu/five-server/discussions) instead.

**Comment by yandeu** [comment]
Do you use the vscode extension or the npm package of five-server?

It crashes once you click the <img width="19" alt="devices" src="https://github.com/yandeu/five-server/assets/20306025/35449828-73d4-487b-a11d-b864df113ee2"> icon?

**Comment by garma21** [comment]
Use extension.
yes,
<img width="19" alt="295656459-35449828-73d4-487b-a11d-b864df113ee2" src="https://github.com/yandeu/five-server/assets/32247965/f32f1d5b-2d05-48bc-8fda-6060f6970ba1">

**Comment by yandeu** [comment]
Ok. How does it crash? Do you get an error message in the console?

**Comment by garma21** [comment]
error - there is no Internet, I found what the problem is, in devtools, in the network tab, you need to turn on the flag - turn off the cache. After that, it seems that everything works stably
