### ISSUE TITLE
Paths in HTML aren't resolved relative to --open=PATH

### ISSUE THREAD

**Issue by feljx** [yandeu/five-server#13]
When using the `--open=PATH` option, for example if serving from `src` folder, paths in `index.html` aren't resolved relative to `src`. E.g. `<link rel="stylesheet" type="text/css" href="styles.css" media="screen" />` will not find the CSS file because it is not located at root but under `src`.

`live-server` does this automatically.
Unfortunately this prevents me from using the module. :/

**Comment by yandeu** [comment]
`open` is only for opening the browser.
You have to set `root` for this.

Also, have a look at [/src/types.ts](https://github.com/yandeu/five-server/blob/main/src/types.ts).

**Comment by feljx** [comment]
Thanks, that exactly what I needed. :)
