### ISSUE TITLE
Notification issue on firefox browser does not work

### ISSUE THREAD

**Issue by Mrc-Junior** [yandeu/five-server#144]
I have an issue with notification after save the file on firefox, the notifications does not work !
Then after save file on vscode, I get an (ALERT permission on firefox) this occurs every time.
![Screenshot 2024-08-17 085434](https://github.com/user-attachments/assets/2647390f-ac6c-4c5b-a153-4ae3c8ab27c8)

**Comment by yandeu** [comment]
Try to go to `http://localhost:5500` instead of `http://127.0.0.1:5500`

**Comment by yandeu** [comment]
I don't use PHP. But is this not a normal behavior if you reload a page which just made a POST request?

**Comment by Mrc-Junior** [comment]
with localhost:5500 work fine thanks !

**Comment by yandeu** [comment]
You're welcome :)
