### ISSUE TITLE
fiveserver.config.js Add the ability to apply params on all startup urls

### ISSUE THREAD

**Issue by ashtonlamont** [yandeu/five-server#147]
When in test, dev, staging, and prod. Many development shops need to apply parameters differently to start up code in precise mode to avoid running all production code as an example. It would be nice to have the ability to have every link start up with a "?mode=[test|dev|prod]" ability to customize this string and be appended to all urls when five server resets after a code update.

The bug is that when I type in what I want manually in the browser, on some rare occasions the params on the URL disappear  while i am actively editing the URL.  I haven't figured out what changes make a URL/fiveserver do a full reset and drop the params.  In our use case this triggers an unwanted to call to a production switch in the code using up a valuable instance in the prod system. If a developer doesn't catch this quickly, five server is reacting to every key stroke and updating the page costing the pool in production to be quickly exhausted. The pool is a fixed size for production and test uses a different method to simulate prod.  

My wishlist would be something like this sample in the config and applied to all pages.

`
module.exports = {
  https:true, 
  root: "public",
  open: false,
  port: 5050,
  params: "?mode=dev&tester=ashton&..."
}`

Ashton Lamont
CIO @ Cobras Solutions

ps. Overall extension is great! Like your work!

**Comment by ashtonlamont** [comment]
I typically get it from vscode. I know some devs do everything through npm.

Ashton

**Comment by yandeu** [comment]
I think a simple middleware inside `fiveserver.config.cjs` would be the easiest way to achieve your goal without changing the source code:

```cjs
module.exports = {
  middleware: [
    (req, res, next) => {
      if (!req.query.mode && !req.query.tester) {
        return res.redirect(req.url + '?mode=dev&tester=ashton')
      } else {
        next()
      }
    }
  ]
}
```

**Comment by yandeu** [comment]
I guess this has been solved using a custom middleware.
