### ISSUE TITLE
Broken badge

### ISSUE THREAD

**Issue by curran** [yandeu/five-server#18]
Greetings, I was evaluating whether or not to use this as a replacement for [https://github.com/tapio/live-server](https://github.com/tapio/live-server) and the first thing I noticed was this broken badge, which gives a bad impression:

![image](https://user-images.githubusercontent.com/68416/123623151-1f6d5280-d7db-11eb-9f2b-f0c85a6943df.png)

I would suggest to remove it. Thanks for your work on this!

**Comment by yandeu** [comment]
Thanks for reporting and considering the switch to Five Server.

The badge is not broken. I use shields.io. Not all request are always fulfilled. That is normall. Free services like shields are not always reliable.

**Comment by curran** [comment]
Aha! Indeed, it's working now. Must have been a temporary glitch.
