### ISSUE TITLE
PHP Error: Command failed

### ISSUE THREAD

**Issue by jcamachott** [yandeu/five-server#22]
Bug: This doesn't work for me. I've gotten this error:

PHP ERROR
error: Command failed: "W:\wamp64\bin\php\php7.3.12\php.exe" "d:\webs\wise\webdev\home\index.php"

My path to php is correct. My php file path is correct. Any ideas? I also have the php.ini setup in settings and I have BOTH a .fiveserverrc.json and a fiveserver.config.js setup on the root

**Comment by yandeu** [comment]
Can you share your config file and the exact error message of five server?

**Comment by yandeu** [comment]
You should only use one config file. JS or JSON.

Do you use double backslash (`\\`) like in the docs?
```js
module.exports = {
  php: '/usr/bin/php', // Linux/macOS (example)
  php: 'C:\\xampp\\php\\php.exe' // Windows (example)
}
```

**Comment by yandeu** [comment]
Did you solve it?
