### ISSUE TITLE
Setting Chrome as browser does not work on Mac

### ISSUE THREAD

**Issue by guppyplopp** [yandeu/five-server#23]
Setting Chrome as browser does not work on MacOS 11.2.1 
Default browser (Safari) is opened instead. 

Terminal output: 
  Five Server running at:
  > Local:    http://localhost:5555
  > Network:  http://10.0.1.90:5555
Could not open browser "chrome". Trying the default browser next.

Settings.json
{
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": true,
    "workbench.editorAssociations": {
        "*.png": "luna.editor",
        "*.jpg": "luna.editor"
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "liveServer.settings.CustomBrowser": "chrome",
    "liveServer.settings.donotVerifyTags": true,
    "editor.minimap.enabled": false,
    "fiveServer.browser": [
    "chrome"
    ]
}

VS Code:
Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.3.0

**Comment by yandeu** [comment]
Try `[ "google chrome" ]` or `[ "google-chrome" ]`.

**Comment by guppyplopp** [comment]
Thanks! 
”google chrome” worked. 


Pål Walfridsson
Darktown Production
Högsbogatan 29
414 75  Göteborg
+46 708 701489
http://darktown.se

**Comment by yandeu** [comment]
> Thanks! ”google chrome” worked.

Glad to hear!

---

Btw, if you reply by mail, make sure you do not send any personal information in your signature.

I have removed your comment since you shared your address and phone number.

**Comment by DBAKANG-GIT** [comment]
> google

google chrome worked for me! Thank you
