### ISSUE TITLE
Error in read only file setting.json

### ISSUE THREAD

**Issue by feferd** [yandeu/five-server#29]
Extension is working fine. There is minor glitch in read only settings.json file.
I do not know what this file settings,json \0. i searched in settings.json and could not find white lines in it.
so maybe not even an error. dont know.

Picture says it all

![image](https://user-images.githubusercontent.com/2869725/141205957-6fa89159-9b66-4b56-83e2-dcc454c93079.png)

**Comment by yandeu** [comment]
Thanks for reporting.

The extension and the configuration area works well?

Looks more like a VSCode bug caused by `"markdownDescription"` in [package.json](https://github.com/yandeu/five-server-vscode/blob/main/package.json)
