### ISSUE TITLE
Comments are being run along with the webpage code

### ISSUE THREAD

**Issue by Codesalot** [yandeu/five-server#31]
When I start the server, commented out HTML is run like normal HTML and CSS. I reloaded the workspace and had the same issue.
Help is appreciated!

**Comment by yandeu** [comment]
Solved?

**Comment by Codesalot** [comment]
No, I am still having the same problem, I did not know if they would decide
I had given enough information...😂

**Comment by yandeu** [comment]
I need some more information. Maybe some screenshots?

**Comment by Codesalot** [comment]
Okay... Here
![page](https://user-images.githubusercontent.com/90432252/141856452-45634319-3b9b-4792-b08d-96cc33f2a619.png)
![code](https://user-images.githubusercontent.com/90432252/141856455-4a96bebd-6fc2-4137-9e47-ea42ea912743.png)
This is in Microsoft Edge.

**Comment by yandeu** [comment]
I see.
Well, you always have to declare your doctype on the first line of your .html file.

See:

> All HTML documents must start with a <!DOCTYPE> declaration.
>
> The declaration is not an HTML tag. It is an "information" to the browser about what document type to expect.

**Comment by Codesalot** [comment]
So it runs commented code because of that?

**Comment by yandeu** [comment]
Yes, probably.

**Comment by Codesalot** [comment]
Okay, thank you!
