### ISSUE TITLE
WebSocket connection fails when url doesn't end with /

### ISSUE THREAD

**Issue by saitonakamura** [yandeu/five-server#32]
**Describe the bug**
When route doesn't end with `/` (say `/my/route`), this line doesn't replace it with `/fwsw`. I also don't understand what is the idea behind replacing part of pathname instead of just using `/fsws` after the host

**Comment by yandeu** [comment]
Like this?

```diff
  // https://github.com/yandeu/five-server/blob/main/client/injected.ts

  const script = document.querySelector('[data-id="five-server"]') as HTMLScriptElement
  const protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://'
- const address = `${protocol}${new URL(script.src).host}${window.location.pathname.replace(/\/+$/gm, '/fsws')}`
+ const address = `${protocol}${new URL(script.src).host}/fsws`
```

**Comment by saitonakamura** [comment]
Yeah

**Comment by yandeu** [comment]
I can't remember why I did this. All tests are passing.

**Comment by yandeu** [comment]
Found it https://github.com/yandeu/five-server/commit/4a3327b2ddbcac41b92bffd2fff1d5b2dcdb9d03#diff-4a1eadd1b9a9e08a65cbc0cca97b8ec321f7a33ded736e102fbcbfd167865757

**Comment by yandeu** [comment]
Fixed in #32

**Comment by saitonakamura** [comment]
@yandeu would be so kind and release it to npm?

**Comment by yandeu** [comment]
Done

**Comment by saitonakamura** [comment]
Great, ty!
