### ISSUE TITLE
"Specification mandates value for attribute async" when attempting to link a local SVG

### ISSUE THREAD

**Issue by ChildishGiant** [yandeu/five-server#38]
**Describe the bug**
When using an SVG as an IMG src it never loads. If one visits the URL they see this: 
![image](https://user-images.githubusercontent.com/13716824/144319295-dd5ddfd5-b8e4-4461-a32c-fa0e427e16c8.png)
The line and column listed is just the end of the file

**Comment by yandeu** [comment]
- Can you please provide more information?
- Can you please post a simplified/compact version of your html file?
