### ISSUE TITLE
All multi-byte functions do not work

### ISSUE THREAD

**Issue by yandeu** [yandeu/five-server#41]
Hey! Me again. In short, I'm trying to work with multi-byte functions, but the server gives an error, not a syntax one.
![изображение_2021-12-08_190412](https://user-images.githubusercontent.com/84411333/145241573-b872ded3-46e0-47c3-82b6-bf8a1df2cf60.png)

_Originally posted by @DigiRon4ik in https://github.com/yandeu/five-server/discussions/40_

**Comment by DigiRon4ik** [comment]
I solved the problem. The matter was that for some reason the php.ini file was not downloaded from me, I downloaded it from the github and included the "mbstring" module in it.
