### ISSUE TITLE
Add Trailing Slash in the Default Index Page

### ISSUE THREAD

**Issue by hclj37** [yandeu/five-server#51]
**Describe the bug**

see the two screenshots below. ❤️

![image](https://user-images.githubusercontent.com/30150098/155491385-154d4f56-a956-4b88-9de8-20d0e236cd16.png)
![image](https://user-images.githubusercontent.com/30150098/155491500-5ab2adfb-c6b0-4489-969b-e114b474be0c.png)

**Have a question?**
Join the [discussions](https://github.com/yandeu/five-server/discussions) instead.

**Comment by yandeu** [comment]
Is there a `index.html` file inside `search-results`?

**Comment by hclj37** [comment]
Yes, there is a `index.html`.

**Comment by yandeu** [comment]
But if you manually type `http://192.168.0.104:5555/search-results/` (with slash) it loads correctly?
