### ISSUE TITLE
Regression in 0.1.3, cannot be used with yarn

### ISSUE THREAD

**Issue by hyperknot** [yandeu/five-server#55]
**Describe the bug**

0.1.3 cannot be used with yarn. Running `yarn five-server` does the following on macOS:
```
env: node\r: No such file or directory
```

0.1.2 works perfectly.

The reason I believe is some Windows line ending CRLF might have sneaked in either in Git source or in the npm generation.
Running dos2unix on the file fixes it.

**Comment by yandeu** [comment]
I don't know. Could it be a yarn issue? `npx five-server@0.1.3 .` seems to work.

**Comment by hyperknot** [comment]
Based on the article, npx silently changes things to the right ending. yarn doesn't.

**Comment by yandeu** [comment]
So everything should be `lf`?

**Comment by hyperknot** [comment]
Yes, I believe that's it. Your prettier changes might be all that's needed.

**Comment by yandeu** [comment]
I found this https://github.com/Microsoft/TypeScript/issues/29928

**Comment by yandeu** [comment]
Can you please try v0.1.4?

**Comment by hyperknot** [comment]
0.1.4 works perfectly, thanks for the quick fix!

**Comment by yandeu** [comment]
You're welcome 😁
