### ISSUE TITLE
Adding query params to html file disables live browser reloading

### ISSUE THREAD

**Issue by realview** [yandeu/five-server#64]
**Describe the bug**

Query parameters after the HTML file breaks live reloading.

**steps to replicate**

in VScode create this  .fiveserverrc file 
`
{
"host":"localhost",
    "open": "index.html?a=b"
  }
`
click "Go Live" 
modify and save index.html 

**results**

- the browser correctly loads  http://localhost/index.html?a=b  ✅ 
-  the change to index.html is logged in the terminal ✅
- **the browser does not refresh to reflect the changes** ❌

### suggestion ###
add a query config item, ie:

`
{
"host":"localhost",
    "open": "index.html",
"query":"?a=b"
  }
`

**Comment by yandeu** [comment]
Thanks for reporting. Should already be fixed :)
