### ISSUE TITLE
Browser is not Updating without first Saving

### ISSUE THREAD

**Issue by AJamesLiptak** [yandeu/five-server#9]
Hi, Yannick.

I really don't want to be _that_ guy, but I have to report that, for me, the **instant-update** feature of your extension is not working -- I have to **Save** the .html file for changes to take place in the browser (Firefox 88.01 (64-bit) if that makes any difference).

I am using **VSCode Version: 1.56.0**, and I confirmed I have only **Five Server v0.0.29** installed.

I followed to the letter the instructions under **Quick Test,** with no luck.

Tried uninstalling / re-installing Five Server, and the same with VSCode as a whole, all with the same result: No instant-update taking place in the browser.

**Comment by yandeu** [comment]
Try https://youtu.be/3-zKYNrxKOk

*I should probably add this and the other videos to the description.*

**Comment by AJamesLiptak** [comment]
Thank you. It works, and I was able to confirm that changes take place when using Emett. (I don't know --- I was half expecting Emett to _not_ work ....)

I'm guessing it's necessary to create _.fiverserverrc.json_ for every project?



> 
> 
> Try https://youtu.be/3-zKYNrxKOk
> 
> _I should probably add this and the other videos to the description._

Yes, most definitely include the link in the Description, for other like me who are not as code-savvy.

Thanks again!

**Comment by yandeu** [comment]
> I'm guessing it's necessary to create _.fiverserverrc.json_ for every project?

For now, yes.

> Also, can I disable the Terminal opening up when launching _Fiver Server_?

Will add this option in a future version.

> Yes, most definitely include the link in the Description, for other like me who are not as code-savvy.

Done. Will be visible with the next update.


> Thanks again!

My pleasure :)

**Comment by yandeu** [comment]
> Also, can I disable the Terminal opening up when launching _Fiver Server_?

Just added this feature. Will be available in the next update.
