### ISSUE TITLE
POST Error with php

### ISSUE THREAD

**Issue by yasarkaancan** [yandeu/five-server#91]
Hi, i discovered that I can't receive posts with php in five-server I think this could be a bug. The problem is in five-server because when I tried it in `php -S localhost:2222` I could receive posts.

**Comment by yandeu** [comment]
This is normal. Please read https://github.com/yandeu/five-server-with-php#why

**Comment by yasarkaancan** [comment]
Ok thanks ! My problem .

**Comment by muava12** [comment]
so the solving is to not use five-server to do POST request?

**Comment by yandeu** [comment]
> so the solving is to not use five-server to do POST request?

Yes. Five Server can't handle POST request since it doesn't include a PHP server.
The idea was to be able to render PHP to do the design work.

But of course you can run your own PHP server and then use five server with it to be able to live reload (but no Instant Updates).
