### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by AquaNot** [yandeu/five-server#95]
**Describe the bug**

**Have a question?**
Join the [discussions](https://github.com/yandeu/five-server/discussions) instead.
PHP ERROR
Could not find PHP executable.

Install PHP
Download and install [XAMPP](https://www.apachefriends.org/index.html).

Get PHP Path
Follow the steps below to get the path to the PHP executable:

Ubuntu: Enter which php in your Terminal.
macOS: Enter which php in your Terminal.
Windows: Search for php.exe.
Config File Example
// fiveserver.config.js
module.exports = {
  php: "/usr/bin/php"              // macOS/Ubuntu
  php: "C:\\xampp\\php\\php.exe"   // Windows
}
i already installed xampp and i already made a fireserver.config.js
![image](https://user-images.githubusercontent.com/82337681/222921564-0f3c56c9-127e-4d19-a644-1b4286428cec.png)
![image](https://user-images.githubusercontent.com/82337681/222921577-65799066-36bd-4cfb-814c-d36832039739.png)
my php path is c:\\xampp\\php\\php.exe if you can help please do.

**Comment by yandeu** [comment]
I believe in your case it should be:

```js
module.exports = {
  php: "C:\\xampp\\php\\php.exe"
}
```

**Comment by Orange661** [comment]
> I believe in your case it should be:
> 
> ```js
> module.exports = {
>   php: "C:\\xampp\\php\\php.exe"
> }
> ```

i know that i already did that and it still doesnt work i do not know why :(

**Comment by AbdallahFSher** [comment]
Were you able to resolve this issue?

**Comment by AbdallahFSher** [comment]
> Were you able to resolve this issue?

I resolved for myself: I was working on a remote server and it didn't like that. Created a local copy and it worked just fine

**Comment by AquaNot** [comment]
> > Were you able to resolve this issue?
> 
> I resolved for myself: I was working on a remote server and it didn't like that. Created a local copy and it worked just fine

Okay ig i will try it
